matrix:
  include:
    - language: cpp
      dist: xenial
      sudo: false
      compiler:
        - gcc

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libeigen3-dev

      before_install:
        - cd rerf/packedForest

      script:
        - make
        - cd test
        - make

    - language: python
      dist: xenial
      python:
        - "3.6"

      addons:
        apt:
          packages:
            - libeigen3-dev

      before_install: cd rerf 
      install:
        - pip install -r requirements.txt
        - pip install -U pytest pytest-cov codecov
        - cd ..
      script:
        - pytest

      after_success:
      - codecov
